# name: Keep Render App Alive

# on:
#   schedule:
#     - cron: '*/10 * * * *' # every 10 minutes
#   workflow_dispatch: # manually trigger the workflow

# jobs:
#   keep-alive:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Ping Render App
#         run: |
#           URL="https://stonks-7s4w.onrender.com"
#           echo "Pinging $URL"

#           RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" $URL)
#           echo "Response: $RESPONSE"

#           if [ $RESPONSE -ne 200 ]; then
#             echo "Failed to ping $URL"
#             exit 1
#           fi